version: '3.8'
services:
  db:
    image: postgres:14.5
    ports:
      - 127.0.0.1:5432:5432
    expose:
      - 5432
    env_file: 
      - .env
    volumes: 
      - ./pginit.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./data/db/:/var/lib/postgresql/data/
  redis:
    image: redis:7
    ports:
      - 127.0.0.1:6379:6379
    expose:
      - 6379
  api:
    image: ghcr.io/tasgon/observable_web:latest
    # build: ../backend
    volumes:
      - /etc/letsencrypt:/opt/certs
    env_file:
      - .env
    ports:
      - 8082:8080
    depends_on:
      - db
      - redis
