version: '3.8'
services:
  db:
    image: docker.io/postgres:14.5
    ports:
      - 127.0.0.1:5432:5432
    expose:
      - 5432
    env_file: 
      - .env
    volumes: 
      - ./pginit.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./data/db/:/var/lib/postgresql/data/
  nginx:
    image: docker.io/nginx:1.23
    ports:
      - 8082:8443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/opt/certs
    depends_on:
      - api
  api:
    # image: ghcr.io/tasgon/observable_web:latest
    build: ../backend
    env_file:
      - .env
    expose:
      - 8080
    depends_on:
      - db
